### ISSUE TITLE
[TOOL] - Docker on Windows 10

### ISSUE THREAD

**Issue by virgo44** [azerothcore/forum#136]
Hi there, I'm trying to test AzerothCore inside docker on Windows 10 LTSC Entreprise v2004.
I follow your topic here: https://www.azerothcore.org/wiki/Install-with-Docker
Actually, I launch "./bin/acore-docker-build" inside a Git Bash command, and I got this issue:

`$ ./bin/acore-docker-build
#1 [internal] load .dockerignore
#1 transferring context: 159B 0.0s done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.62kB 0.0s done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/ubuntu:20.04
#3 DONE 1.3s

#4 [1/8] FROM docker.io/library/ubuntu:20.04@sha256:bc2f7250f69267c9c6b66d7...
#4 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 268.86MB 3.7s
#6 transferring context: 393.87MB 7.5s done
#6 DONE 7.6s

#5 [2/8] RUN apt update && apt install -y git cmake make gcc g++ clang libm...
#5 CACHED

#7 [3/8] ADD .git /azerothcore/.git
#7 DONE 3.2s

#8 [4/8] ADD deps /azerothcore/deps
#8 DONE 0.4s

#9 [5/8] ADD conf/dist /azerothcore/conf/dist
#9 DONE 0.0s

#10 [6/8] ADD src /azerothcore/src
#10 DONE 0.8s

#11 [7/8] ADD modules /azerothcore/modules
#11 DONE 0.0s

#12 [8/8] ADD CMakeLists.txt /azerothcore/CMakeLists.txt
#12 DONE 0.0s

#13 exporting to image
#13 exporting layers
#13 exporting layers 1.2s done
#13 writing image sha256:d449bd37f043424a1d45c3e1c7391d2a6d75278d0557396cbf4ecf08f1bff768 done
#13 naming to docker.io/library/acbuild done
#13 DONE 1.2s
docker: Error response from daemon: status code not OK but 500:     System.Exception
                                                                                        ClassNameMessageDataInnerExceptionHelpURLSWatsonBuckets)System.Collections.ListDictionaryInternalSystem.ExceptiSystem.ExceptionXThe notification platform is unavailable.

The notification platform is unavailable.

¼   at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
   at Docker.WPF.PromptShareDirectory.<PromptUserAsync>d__6.MoveNext() in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.WPF\PromptShareDirectory.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__6.MoveNext() in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
≈8
CreateToastNotifier
Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
Windows.UI.Notifications.ToastNotificationManager
Windows.UI.Notifications.ToastNotifier CreateToastNotifier(System.String)>Ç
)System.Collections.ListDictionaryInternalheadversioncount8System.Collections.ListDictionaryInternal+DictionaryNode   8System.Collections.ListDictionaryInternal+DictionaryNodekeyvaluenext8System.Collections.ListDictionaryInternal+DictionaryNode      RestrictedDescription
+The notification platform is unavailable.

       RestrictedErrorReference
RestrictedCapabilitySid
       __RestrictedErrorObject          (System.Exception+__RestrictedErrorObjec"__HasRestrictedLanguageErrorObjec.
See 'docker run --help'.`

Note that if I try to use the 'Windows' commands you suggest, it does not work: "bash bin\acore-docker-build", I got this message: "bash: binacore-docker-generate-etc: No such file or directory" (no antislash between bin and acore-...), so the command is not working)

What's wrong? What should I have to do?

Thanks for help

V.

**Comment by locus313** [comment]
Welcome @virgo44!
The forum is actually not the right place to ask for help, please see this topic and we'll be glad to help you!
https://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by virgo44** [comment]
oh I'm sorry... i will post on StackOverflow. Sorry again. Thanks
